### ISSUE TITLE
Crashes on launching modpack

### ISSUE THREAD

**Issue by anoomolu** [MCTeamPotato/FlameSweeping#1]
Hiya. I made a new 1.16.5 forge instance with only Flame Sweeping 0.0.1, and unfortunately it's crashing.

https://mclo.gs/NfR9QPw is my latest log.

**Comment by anoomolu** [comment]
welp seems like I'm having the same problem with Java 8 as well.

**Comment by Kasualix** [comment]
fixed in 1.0.0
forget to watch this repo and didn't receive the crash issue...
